name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: arbit_hub_linux
            asset_name: arbit_hub
          - os: windows-latest
            artifact_name: arbit_hub_windows
            asset_name: arbit_hub.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-deb (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: cargo install cargo-deb

    - name: Build
      run: cargo build --release --verbose

    - name: Package .deb (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: cargo deb

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          target/release/${{ matrix.asset_name }}
          target/debian/*.deb
